name: kalti
description: "This Flutter application is designed to provide users with a seamless and interactive experience through a custom navigation drawer. The app offers various sections including Home, Contact, Energy Services, Videos, Gallery, About Us, Blog, and essential legal pages like Terms & Conditions and Privacy Policies. Built using the GetX package for efficient state management and navigation, it also integrates features such as app sharing and in-app ratings. With a clean, user-friendly interface and intuitive design, the app ensures that users can easily access diverse content and services while enjoying smooth performance and modern aesthetics."
publish_to: 'none'

version: 1.0.1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  get: ^4.6.6 # State Management!
  get_it: ^8.0.2
  url_launcher: ^6.3.0
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.3.1
  webview_flutter_wkwebview: ^3.18.0
  flutter_inappwebview: ^6.1.5
  intl: ^0.20.0
  image: ^4.3.0
  carousel_slider: ^5.0.0
  share_plus: ^10.1.4
  connectivity_plus: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
